(function () {
  "use strict";
  var pathMatch = location.pathname.match(/^\/polycule\/([^/]+)$/);
  var id = (pathMatch && pathMatch[1]) || location.hash.slice(1) || "default", password = sessionStorage.getItem("bgplay-password-" + id) || "";
  var creating = location.pathname === "/new";
  var panel = document.createElement("section"); panel.style.cssText = "margin:8px;padding:10px;border:1px solid #ccc;font:13px system-ui;max-width:520px";
  panel.innerHTML = creating ? "<strong>Create a polycule</strong><form class='new' style='margin:8px 0'><button>Create</button> <input name='password' type='password' placeholder='Optional edit password'></form>" : "<strong>Polycule editor</strong> <code>" + id + "</code><form class='new' style='margin:8px 0'><button>Create a new polycule</button> <input name='password' type='password' placeholder='Optional edit password'></form><form class='add'><input name='id' placeholder='ID, e.g. node-alex' required> <input name='name' placeholder='Display name' required> <button>Add person</button></form><form class='addrel' style='margin:8px 0'><select name='source'></select> <select name='target'></select> <input name='type' value='relationship' placeholder='Relationship type'> <button>Add relationship</button></form><div class='list'></div><div class='rels'></div>";
  function ask(){ password = prompt("Editor password for this polycule:", password || "") || ""; sessionStorage.setItem("bgplay-password-" + id, password); }
  function req(url, opt){ opt=opt||{}; opt.headers=opt.headers||{}; if(password) opt.headers["X-BGPlay-Password"]=password; return fetch(url,opt).then(function(r){return r.json().then(function(b){if(!r.ok)throw Error(b.error||"Request failed");return b;});}); }
  function render(){ req("/api/polycules/"+encodeURIComponent(id),{headers:{}}).then(function(doc){ var options=doc.people.map(function(p){return "<option value='"+p.id+"'>"+p.name+"</option>";}).join(""); panel.querySelector(".addrel [name=source]").innerHTML=options; panel.querySelector(".addrel [name=target]").innerHTML=options; panel.querySelector(".list").innerHTML=doc.people.map(function(p){return "<div>"+p.name+" <code>"+p.id+"</code> <button data-id='"+p.id+"'>Remove</button></div>";}).join(""); panel.querySelector(".rels").innerHTML=doc.relationships.map(function(r){return "<div>"+r.source+" — "+r.target+(r.end ? " (ended) <button data-revert='"+r.id+"'>Revert breakup</button>" : " <button data-breakup='"+r.id+"'>Break up</button>")+" <button data-rel='"+r.id+"'>Remove relationship</button></div>";}).join(""); }); }
  document.addEventListener("DOMContentLoaded",function(){ document.body.insertBefore(panel,document.body.firstChild);
    panel.querySelector(".new").onsubmit=function(e){e.preventDefault();var f=e.target;fetch("/api/polycules",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({password:f.elements.password.value})}).then(function(r){return r.json();}).then(function(x){location.href=x.url;});};
    if (creating) return;
    panel.querySelector(".add").onsubmit=function(e){e.preventDefault();if(!password)ask();var f=e.target;req("/api/polycules/"+encodeURIComponent(id)+"/people",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:f.elements.id.value,name:f.elements.name.value})}).then(function(){location.reload();}).catch(function(e){alert(e.message);});};
    panel.querySelector(".addrel").onsubmit=function(e){e.preventDefault();if(!password)ask();var f=e.target;req("/api/polycules/"+encodeURIComponent(id)+"/relationships",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({source:f.elements.source.value,target:f.elements.target.value,type:f.elements.type.value})}).then(function(){location.reload();}).catch(function(e){alert(e.message);});};
    panel.querySelector(".list").onclick=function(e){var pid=e.target.dataset.id;if(!pid||!confirm("Remove this person and their relationships?"))return;if(!password)ask();req("/api/polycules/"+encodeURIComponent(id)+"/people/"+encodeURIComponent(pid),{method:"DELETE"}).then(function(){location.reload();}).catch(function(e){alert(e.message);});}; render(); });
    panel.querySelector(".rels").onclick=function(e){var bid=e.target.dataset.breakup,undo=e.target.dataset.revert,rid=e.target.dataset.rel;if(!bid&&!undo&&!rid)return;if(!password)ask();if(bid){if(!confirm("Record this breakup now?"))return;req("/api/polycules/"+encodeURIComponent(id)+"/relationships/"+encodeURIComponent(bid)+"/breakup",{method:"POST"}).then(function(){location.reload();}).catch(function(e){alert(e.message);});return;}if(undo){req("/api/polycules/"+encodeURIComponent(id)+"/relationships/"+encodeURIComponent(undo)+"/revert-breakup",{method:"POST"}).then(function(){location.reload();}).catch(function(e){alert(e.message);});return;}if(!confirm("Permanently remove this relationship and its history?"))return;req("/api/polycules/"+encodeURIComponent(id)+"/relationships/"+encodeURIComponent(rid),{method:"DELETE"}).then(function(){location.reload();}).catch(function(e){alert(e.message);});};
}());
